server.port=8081
spring.application.name=ms-vidasalud-catalogo

# Base de datos H2 local
spring.datasource.url=jdbc:h2:mem:catalogdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Consola de H2
spring.h2.console.enabled=true

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Diferir la inicialización SQL para que la tabla exista antes de insertar
spring.jpa.defer-datasource-initialization=true

# ── Azure AD / Entra ID ────────────────────────────────────
azure.issuer-uri=https://login.microsoftonline.com/a02c872a-3746-4efc-a2e3-1f8e608b99e4/v2.0
azure.jwk-set-uri=https://login.microsoftonline.com/a02c872a-3746-4efc-a2e3-1f8e608b99e4/discovery/v2.0/keys
# audiencia del access token: Azure AD v2.0 emite el Application ID (GUID).
azure.audience=6db95f4d-96a5-47ca-bc8e-e43bd5eda9ab