server.port=8082
spring.application.name=ms-vidasalud-atenciones

# Configuracion H2
spring.datasource.url=jdbc:h2:mem:atencionesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# Hibernate & Scripts SQL
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

# Swagger / OpenAPI
springdoc.packages-to-scan=com.vidasalud

# ── Azure AD / Entra ID ────────────────────────────────────
azure.issuer-uri=https://login.microsoftonline.com/a02c872a-3746-4efc-a2e3-1f8e608b99e4/v2.0
azure.jwk-set-uri=https://login.microsoftonline.com/a02c872a-3746-4efc-a2e3-1f8e608b99e4/discovery/v2.0/keys
# audiencia del access token: Azure AD v2.0 emite el Application ID (GUID).
azure.audience=6db95f4d-96a5-47ca-bc8e-e43bd5eda9ab