server.port=8082
spring.application.name=ms-vidasalud-atenciones

# Configuracion H2
spring.datasource.url=jdbc:h2:mem:atencionesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# Hibernate & Scripts SQL
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

# Swagger / OpenAPI
springdoc.packages-to-scan=com.vidasalud